export const config = {
  whmcsUrl: process.env.WHMCS_URL || 'https://bshopafrica.com/billing',
  whmcsIdentifier: process.env.WHMCS_IDENTIFIER || 'XOzQQWD7BneW7NWNIpATh0wW0YWtaIlg',
  whmcsSecret: process.env.WHMCS_SECRET || 'pkL8ESq1jUzXSjuUBPnPfgquaQPCEZnT',
  pawapayApiKey: process.env.PAWAPAY_API_KEY || '',
  pawapayEnvironment: process.env.PAWAPAY_ENVIRONMENT || 'production',
  adminPassword: process.env.ADMIN_PASSWORD || 'admin123',
  databaseUrl: process.env.DATABASE_URL || 'mysql://bshopafrica_cms_admin:qLinT{aOE%fS@localhost:3306/bshopafrica_cms',
  appUrl: process.env.NEXT_PUBLIC_APP_URL || 'https://test.bshopafrica.com',
  websiteBuilderProductId: process.env.WEBSITE_BUILDER_PRODUCT_ID || '34',
  smtpHost: process.env.SMTP_HOST || 'mail.bshopafrica.com',
  smtpPort: parseInt(process.env.SMTP_PORT || '465', 10),
  smtpUser: process.env.SMTP_USER || 'admin@bshopafrica.com',
  smtpPass: process.env.SMTP_PASS || 'qLinT{aOE%fS',
  whmHost: process.env.WHM_HOST || 'https://s12759.usc1.stableserver.net:2087',
  whmUser: process.env.WHM_USER || 'bshopafrica',
  whmToken: process.env.WHM_TOKEN || 'GDFFJ2O94Q3EBRWM0I3EJIU9TRZ9GZL6',
}
